### ISSUE TITLE
[Feature Request] Ground-Based Heavy Vehicles Can Smash and Destroy “Less Solid” Blocks on Impact

### ISSUE THREAD

**Issue by light-chimes** [Mercurows/SuperbWarfare#15]
Hello SuperbWarfare team!

First of all, I absolutely love this mod. Beyond its outstanding art style and gameplay, I’m a longtime fan of the mcheli mod in older Minecraft versions, which delivers an amazing vehicle experience. Thanks to SuperbWarfare, I can enjoy similarly excellent vehicles in the latest versions!

**Feature Proposal:**
In mcheli, when driving heavy ground vehicles (such as tanks), if the vehicle charges into certain less-solid blocks—like grass, saplings, and simple wooden fences—**those blocks are smashed and destroyed on impact**. I think adding a similar mechanic to SuperbWarfare would:

**Improve Traversability:** Vehicles could power through undergrowth and light obstacles without getting frustratingly stuck, especially in dense forests or beside wooden fences.

**Match Intuitive Expectations**: A heavy vehicle naturally smashes weaker blocks, emphasizing the difference between traveling on foot and driving.

**Enhance Fun**: There’s something satisfying and immersive about watching blocks shatter under the force of a charging tank!

If there are concerns about unintended side effects, perhaps this could be an optional, configurable feature (e.g., an on/off toggle or a block whitelist/blacklist).

Whatever, thank you for your outstanding work on SuperbWarfare! I’m excited to see where this mod goes next and would be grateful for any consideration of this feature. 😀

**Comment by LightQuanta** [comment]
Can't u just check out `saves/(your world)/serverconfig/superbwarfare-server.toml`

```toml
[vehicle]
	#Allows vehicles to destroy blocks via collision
	collision_destroy_blocks = false
	#Allows vehicles to destroy hard blocks via collision
	collision_destroy_hard_blocks = false
	#Allow vehicles to pick up items
	vehicle_item_pickup = true
	#List of entities that can be damaged by collision
	collision_entity_whitelist = []
	#Allows vehicles to destroy blocks via collision like a beast
	collision_destroy_blocks_beastly = false
```

before u ask?

Also u can add tags to blocks like `superbwarfare:soft_collision` and `superbwarfare:hard_collision` by making a datapack in order to allow vehicles to collide more blocks
